apiVersion: 1
deleteDatasources:
  - name: InfluxDB
    orgId: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: group20
    secureJsonData:
      token: super-secret-token
